
## General exception mechanism 
			



<a name="NOTE1"></a>
<a name="NOTE1_1"></a>


## Overview
<a name="overview_ELTTEXTE000233"></a>
A process of general exception is available for all the components of the object with which it is associated. This exception process can be used as long as the object is available.

A process of general exception can be declared in any process. After the execution of an exception process, the WLanguage code following the process is run.

For example:

- If the exception process is declared in the project initialization code, it is valid for any error that occurs in the project.

- If the exception process is declared in the declaration code of the global variables of a window, page or report, it is valid for any error that occurs in the window, in the page, in a window control, in a page control or in a procedure local to the window or to the page. This exception process is not valid anymore when the window or the page is closed.

- If the exception process is declared in any process, it is valid for any error that occurs in this process. This exception process will not be valid anymore once the process is completed. Therefore, an exception process declared in the click code of a button will only be valid in this process and in all the procedures called from this process.




![Java](https://doc.pcsoft.fr/ext/images/us/JAVA.png) Caution: The mechanism of general exceptions is not available.. Only the specific exceptions (WHEN EXCEPTION IN) are available. For more details, see [Management of specific exceptions](../WDLang1/3034003.md).

<a name="NOTE2"></a>
<a name="NOTE2_1"></a>


## Declaring several processes of general exceptions
<a name="declaring_several_processes_general_exceptions_ELTTEXTE000257"></a>


### Declaring the processes of general exceptions in the same process
<a name="declaring_the_processes_general_exceptions_the_same_process_ELTPARAGRAPHE000033"></a>

The second exception process will replace the first exception process from the declaration of second exception process.

**Example**: In the Example procedure, if an error occurs:

- In &lt;Code1&gt;: no management of exceptions is enabled unless an exception procedure was defined in the calling code (in the current window or in the current page or in the project).

- In &lt;Code 2&gt;: the active exception process is &lt;Process of Exception 1>.

- In &lt;Code 3&gt;: the active exception process is &lt;Process of Exception 2>.





```txt
PROCEDURE Example()
<"Code 1">
WHEN EXCEPTION
	<Process of Exception 1>
END
<"Code 2">
WHEN EXCEPTION
	<Process of Exception 2>
END
<"Code 3">
```

<a name="NOTE2_2"></a>


### Declaring the exception processes in different processes
<a name="declaring_the_exception_processes_different_processes_ELTPARAGRAPHE000048"></a>

If the exception processes are declared in embedded objects (project and window, project and page, window and control or page and control for example), the exception process of the smallest object hides the main exception process during the lifetime of this object.

**Example**: If the following two exception processes are declared:

- exception process A declared in the initialization code of a project, 

- exception process B declared in the declaration code of global variables of a window or page.




For all the errors that occur in the window or in the page, the exception process B will be used and it will hide the exception process A.
<a name="NOTE2_3"></a>


### Nesting the exception processes in different processes: managing the exception via a higher level
<a name="nesting_the_exception_processes_different_processes_managing_the_exception_via_higher_level_ELTPARAGRAPHE000062"></a>

If the exception processes are declared in embedded objects (project and window, project and page, window and control or page and control for example), the error can be managed in the exception process of higher level.

All you have to do is use the EXCEPTION keyword in the exception process.

Example:


```wl
// Project initialization code
WHEN EXCEPTION
	// Stop the application
	EndProgram()
END
```



```wl
// Global procedure ControlValue
// Returns the value of the control or "" if the control does not exist
PROCEDURE ControlValue(ControlName)
WHEN EXCEPTION
	// For the UnknownControl error, "" is returned
	IF ExceptionInfo(errCODE) = UnknownControl THEN RESULT ""
	// For another error, the error manager of the project is called
	EXCEPTION
END
```


<a name="NOTE3"></a>
<a name="NOTE3_1"></a>


## Main remarks
<a name="main_remarks_ELTTEXTE000293"></a>


### An exception process can only be used once
<a name="exception_process_can_only_used_once_ELTPARAGRAPHE000079"></a>

An exception process can only be used once. If a second exception occurs, the exception process will not be run. If an exception process of higher level exists, this exception process will be run.

To re-enable an exception process once it has been used, call [ExceptionEnable](../WDLang1/3034002.md). **Caution**: this function must be used with great care.

![WINDEV](https://doc.pcsoft.fr/ext/images/us/WD.png) **For example**: A general exception process was declared at window level and at project level. 
A first programming error occurs in the window. This error is processed by the exception process of the window. 
A second error occurs in the window. This error is processed by the exception process of the project.


<a name="NOTE3_2"></a>


### Quality of  WLanguage code for processing the exception
<a name="quality_wlanguage_code_for_processing_the_exception_ELTPARAGRAPHE000107"></a>

An exception process cannot be used inside a WLanguage exception process. We recommend that you check the quality of the code in the exception processes because any error will trigger the display of the standard window/page of the security mechanism of WLanguage.
<a name="NOTE3_3"></a>


### Quality of the code following an exception process
<a name="quality_the_code_following_exception_process_ELTPARAGRAPHE000114"></a>

After the execution of an exception process, the WLanguage code following the process is run. We recommend that you pay attention to the quality of this code (to avoid displaying an error message).

**Example**: In the following code, {"Control1"}..Value = 5 triggers the exception process. At the end of the exception process, the same line of code is re-run: the exception was already processed and the security mechanism of WLanguage is triggered.


```wl
// Exception process
WHEN EXCEPTION
	// Process to perform if an exception occurs
	Trace("Error")
END
// Programming error: the Control1 control does not exist
{"Control1"}..Value = 5
```


**To avoid this problem, at the end of the exception process, we advise you to**:

- Make sure that the problem is corrected and that it will not happen again.

- Use the RETURN and RESULT keywords to exit from the current process.

- Use [SetFocusAndReturnToUserInput](../WDLang1/1410088107.md) to give control back to the user. 
	

- Use [EndProgram](../WDLang1/3013033.md) to close the application.




<a name="NOTE4"></a>
<a name="NOTE4_1"></a>


## Special case
<a name="special_case_ELTTEXTE000329"></a>
A general exception process cannot be declared in compound statements such as:

- FOR

- LOOP

- WHILE




In this type of statement, use the [specific exception process](../WDLang1/3034003.md).
<a name="NOTE4_2"></a>


### Exception process and component
<a name="exception_process_and_component_ELTPARAGRAPHE000158"></a>

If a general exception process is performed both in the initialization code of the component and in the initialization code of the project containing the component, the exception process of the project will be run when an error occurs in one of the component elements.
<a name="NOTE4_3"></a>


### Exception process and threads
<a name="exception_process_and_threads_ELTPARAGRAPHE000165"></a>

If a general exception process is set in the project initialization code, it will be triggered if an exception occurs:

- in the main thread, 

- in a secondary thread started by [ThreadExecute](../WDLang1/3077024.md).


However, if the secondary thread triggers an exception, it will not be possible to find out its origin with [ExceptionInfo](../WDLang1/3034006.md) in the project code. To find out the origin of an exception in a secondary thread, the exception process must be included in the secondary thread.

<a name="NOTE5"></a>
<a name="NOTE5_1"></a>


## Functions for managing general exceptions
<a name="functions_for_managing_general_exceptions_ELTTEXTE000365"></a>
Functions specific to the management of exceptions can be used with the general exception processes:



|   |   |
| --- | --- |
| [ExceptionDisplay](../WDLang1/1000019408.md) | Displays the standard window of exceptions with the content of the current exception. |
| [ExceptionEnable](../WDLang1/3034002.md) | Re-enables the current exception process if the exception was corrected. |
| [ExceptionInfo](../WDLang1/3034006.md) | Retrieves information about the current exception. |
| [ExceptionPropagate](../WDLang1/3034014.md) | Propagates an exception. |
| [ExceptionRestoreParameter](../WDLang1/3034008.md) | Restores the exception process of a process. |
| [ExceptionThrow](../WDLang1/3034005.md) | Artificially triggers the security mechanism of WLanguage by throwing an exception. |






